dataset:
  CoNLL2003Dataset: examples.conll2003.conll_2003_dataset

iterator_path:
  CoNLLCsvInMemory: examples.conll2003.conll_csv_in_memory

_experiments:

  experiment_name: conll_2003_dataset
  experiment_root_directory: /Users/sampathm/vitaFlow/
  use_char_embd: True

experiments:
  num_epochs: 5
  dataset_name: CoNLL2003Dataset
  data_iterator_name: CoNLLCsvInMemory
  model_name: BiLSTMCrf

  # dataset - details
  CoNLL2003Dataset:
    experiment_root_directory: /Users/sampathm/vitaFlow/
    experiment_name: experiment_name
    preprocessed_data_path: preprocessed_data
    train_data_path: train
    validation_data_path: val
    test_data_path: test
    minimum_num_words: 5
    over_write: False

  # data iterator
  CoNLLCsvInMemory:
    experiment_root_directory: /Users/sampathm/vitaFlow/
    experiment_name: experiment_name
    iterator_name: conll_data_iterator
    preprocessed_data_path: preprocessed_data
    train_data_path: train
    validation_data_path: val
    test_data_path: test
    text_col: 0
    entity_col: 3
    batch_size: 4
    seperator: ~  # potential error point depending on the dataset
    quotechar: ^
    max_word_length: 20
    use_char_embd: True

  # data model
  BiLSTMCrf:
    model_directory: /Users/sampathm/vitaFlow/
    experiment_name: experiment_name
    use_char_embd: True
    learning_rate: 0.001
    word_level_lstm_hidden_size: 12
    char_level_lstm_hidden_size: 12
    word_emd_size: 8
    char_emd_size: 8
    num_lstm_layers: 1
    keep_propability: 0.5

