FROM python:3.6-jessie
LABEL maintainer="Sampath Kumar M"

RUN apt-get update && \
 apt-get install vim -y

COPY ../.. /app
WORKDIR /app

RUN pip install Cython --install-option="--no-cython-compile"

RUN pip install tensorflow

# RUN pip install -r requirements.txt

# RUN python -m spacy download en_core_web_md
